[package]
name = "seyal-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
seyal-render = { path = "../seyal-render" }
seyal-runtime = { path = "../seyal-runtime" }

[lints.rust]
unsafe_code = "deny"
