[package]
name = "seyal-terminal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bench]]
name = "vt_parser_state"
harness = false

[[bench]]
name = "vt_scroll_state"
harness = false

[lints]
workspace = true
